// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KqVfbfxdkGcwx9-vG2EW8Q8Ef14ies4',
    appId: '1:71170030329:web:f02855e3023e527714c028',
    messagingSenderId: '71170030329',
    projectId: 'login-app-s',
    authDomain: 'login-app-s.firebaseapp.com',
    storageBucket: 'login-app-s.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc02mYSRiUpgXwf5Ah1Fh20zdwJShiN-M',
    appId: '1:71170030329:android:3e95c7cc0b02eee014c028',
    messagingSenderId: '71170030329',
    projectId: 'login-app-s',
    storageBucket: 'login-app-s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlEkg16XWIwHA7UllWuaFOFIyNpK1Y-E',
    appId: '1:71170030329:ios:4733ef1734b115ef14c028',
    messagingSenderId: '71170030329',
    projectId: 'login-app-s',
    storageBucket: 'login-app-s.firebasestorage.app',
    iosBundleId: 'com.example.trailer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlEkg16XWIwHA7UllWuaFOFIyNpK1Y-E',
    appId: '1:71170030329:ios:4733ef1734b115ef14c028',
    messagingSenderId: '71170030329',
    projectId: 'login-app-s',
    storageBucket: 'login-app-s.firebasestorage.app',
    iosBundleId: 'com.example.trailer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2KqVfbfxdkGcwx9-vG2EW8Q8Ef14ies4',
    appId: '1:71170030329:web:0d357edd0bd8225b14c028',
    messagingSenderId: '71170030329',
    projectId: 'login-app-s',
    authDomain: 'login-app-s.firebaseapp.com',
    storageBucket: 'login-app-s.firebasestorage.app',
  );

}